### ISSUE TITLE
VehFuncs

### ISSUE THREAD

**Issue by CanerKaraca23** [Fabio3rs/Garage-Save-eXtender#3]
Hey, should we use your latest version on VehFuncs?

300kbs to 2MB.

**Comment by Fabio3rs** [comment]
Hi. I think it should not be a problem.

The size is due to this build be with static flags, so the standard library goes to inside the final binary.

**Comment by CanerKaraca23** [comment]
> Hi. I think it should not be a problem.
> 
> The size is due to this build be with static flags, so the standard library goes to inside the final binary.

Hey @Fabio3rs , thank you for answer! Which version you recommend? The latest gsx or coming with VehFuncs one gsx?

Also, it's off-topic but, do you have the source code of your SAMP FXT Fix mod?
Can you check this: https://github.com/cleolibrary/CLEO5/issues/194#issuecomment-2352338090

**Comment by Fabio3rs** [comment]
> > Hi. I think it should not be a problem.
> > The size is due to this build be with static flags, so the standard library goes to inside the final binary.
> 
> Hey @Fabio3rs , thank you for answer! Which version you recommend? The latest gsx or coming with VehFuncs one gsx?
> 
> Also, it's off-topic but, do you have the source code of your SAMP FXT Fix mod? Can you check this: [cleolibrary/CLEO5#194 (comment)](https://github.com/cleolibrary/CLEO5/issues/194#issuecomment-2352338090)

Thanks.
If I remember correctly, the differences in the versions is some refactors and the build system, it should not afftect the inner works. I would recommend the newer version and if some problem occurs, rollback to the old version.

I think it is this code: https://github.com/Fabio3rs/SAMP-fxt-fix/blob/main/paynspray/main.cpp
